const express = require('express');
const router = express.Router();
const { middleware: query } = require("querymen");
const { middleware: body } = require("bodymen");
const auth = require("../services/auth");
const { selectSemester, save, search } = require("../controllers/schedules.controller");
// router.get('/', query(), index);
router.get("/me/semesters", auth, selectSemester);
router.post("/me/save", auth, save);
router.post("/me/search", auth, search);
module.exports = router;
