const express = require('express');
const router = express.Router();
const auth = require("../services/auth");
const { index, show, create, login, showMe, logout, logoutAll} = require("../controllers/users.controller");
router.get('/', index);
router.post('/', create);
router.post('/login', login);
router.get('/me', auth, showMe);
router.post('/me/logout', auth, logout);
router.post('/me/logoutall', auth, logoutAll);
router.get('/:id', show);
module.exports = router;
